import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Prompt } from 'next/font/google';
import "./globals.css";

// กำหนด metadata อย่างถูกต้อง
export const metadata: Metadata = {
  title: "Create Next App",  // กำหนด title
  description: "Generated by create next app",  // กำหนด description
};

const geistSans = Geist({
  variable: "--font-geist-sans", 
  subsets: ["latin"],
});

const prompt = Prompt({
  weight: '200',
  subsets: ['latin', 'thai'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <head>
      </head>
      <body
        className={`${prompt.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
